<?php
/**
 * Claim Chart PDF Generator
 *
 * @package SynPatPlatform\Modules\PDF\Generators
 */

namespace SynPat\Modules\PDF\Generators;

/**
 * Claim Chart PDF Generator Class
 */
class ClaimChart_PDF {

	/**
	 * Generate claim chart PDF
	 *
	 * @param array $patent_data Patent data.
	 * @param array $options     Generation options.
	 * @return string PDF file path.
	 * @throws \Exception If PDF generation fails.
	 */
	public function generate( $patent_data, $options = array() ) {
		if ( ! class_exists( '\Mpdf\Mpdf' ) ) {
			throw new \Exception( __( 'mPDF library not found. Please install it via Composer.', 'synpat-platform' ) );
		}

		$mpdf = new \Mpdf\Mpdf( array(
			'mode'         => 'utf-8',
			'format'       => 'A4-L',
			'margin_top'   => 15,
			'margin_left'  => 10,
			'margin_right' => 10,
		) );

		$html = $this->generate_html( $patent_data );

		$mpdf->WriteHTML( $html );

		$upload_info = wp_upload_dir();
		$pdf_dir     = $upload_info['basedir'] . '/synpat-pdfs';

		if ( ! file_exists( $pdf_dir ) ) {
			wp_mkdir_p( $pdf_dir );
		}

		$filename = 'claim-chart-' . $patent_data['patent_number'] . '-' . time() . '.pdf';
		$filepath = $pdf_dir . '/' . $filename;

		$mpdf->Output( $filepath, \Mpdf\Output\Destination::FILE );

		return $filepath;
	}

	/**
	 * Generate HTML content for PDF
	 *
	 * @param array $patent_data Patent data.
	 * @return string HTML content.
	 */
	private function generate_html( $patent_data ) {
		ob_start();
		?>
		<!DOCTYPE html>
		<html>
		<head>
			<style>
				body { font-family: Arial, sans-serif; font-size: 10pt; }
				h1 { color: #2c3e50; font-size: 18pt; text-align: center; }
				table { width: 100%; border-collapse: collapse; margin-top: 20px; }
				th, td { border: 1px solid #34495e; padding: 10px; vertical-align: top; }
				th { background-color: #3498db; color: white; font-weight: bold; }
				.claim { width: 50%; }
				.product { width: 50%; background-color: #ecf0f1; }
				.header-info { margin-bottom: 20px; font-size: 9pt; }
			</style>
		</head>
		<body>
			<h1><?php echo esc_html__( 'Claim Chart Analysis', 'synpat-platform' ); ?></h1>

			<div class="header-info">
				<strong><?php echo esc_html__( 'Patent:', 'synpat-platform' ); ?></strong> 
				<?php echo esc_html( $patent_data['patent_number'] ?? 'N/A' ); ?><br>
				<strong><?php echo esc_html__( 'Title:', 'synpat-platform' ); ?></strong> 
				<?php echo esc_html( $patent_data['title'] ?? 'N/A' ); ?>
			</div>

			<table>
				<thead>
					<tr>
						<th class="claim"><?php echo esc_html__( 'Patent Claim', 'synpat-platform' ); ?></th>
						<th class="product"><?php echo esc_html__( 'Product/Prior Art', 'synpat-platform' ); ?></th>
					</tr>
				</thead>
				<tbody>
					<?php
					// Placeholder claim analysis
					for ( $i = 1; $i <= 3; $i++ ) :
						?>
						<tr>
							<td class="claim">
								<strong><?php echo sprintf( esc_html__( 'Claim %d:', 'synpat-platform' ), $i ); ?></strong><br>
								<?php echo esc_html__( 'Claim element placeholder text...', 'synpat-platform' ); ?>
							</td>
							<td class="product">
								<?php echo esc_html__( 'Product feature or prior art reference...', 'synpat-platform' ); ?>
							</td>
						</tr>
					<?php endfor; ?>
				</tbody>
			</table>

			<div style="margin-top: 30px; font-size: 8pt; color: #7f8c8d;">
				<p><?php echo esc_html__( 'Generated by SynPat Platform', 'synpat-platform' ); ?> - <?php echo esc_html( date( 'F j, Y' ) ); ?></p>
			</div>
		</body>
		</html>
		<?php
		return ob_get_clean();
	}
}
