<?php
/**
 * Docket PDF Generator
 *
 * @package SynPatPlatform\Modules\PDF\Generators
 */

namespace SynPat\Modules\PDF\Generators;

/**
 * Docket PDF Generator Class
 */
class Docket_PDF {

	/**
	 * Generate docket PDF
	 *
	 * @param array $patent_data Patent data.
	 * @param array $options     Generation options.
	 * @return string PDF file path.
	 * @throws \Exception If PDF generation fails.
	 */
	public function generate( $patent_data, $options = array() ) {
		// Check if mPDF is available.
		if ( ! class_exists( '\Mpdf\Mpdf' ) ) {
			throw new \Exception( __( 'mPDF library not found. Please install it via Composer.', 'synpat-platform' ) );
		}

		$mpdf = new \Mpdf\Mpdf( array(
			'mode'        => 'utf-8',
			'format'      => 'A4',
			'margin_top'  => 20,
			'margin_left' => 15,
		) );

		$html = $this->generate_html( $patent_data );

		$mpdf->WriteHTML( $html );

		$upload_info = wp_upload_dir();
		$pdf_dir     = $upload_info['basedir'] . '/synpat-pdfs';

		if ( ! file_exists( $pdf_dir ) ) {
			wp_mkdir_p( $pdf_dir );
		}

		$filename = 'docket-' . $patent_data['patent_number'] . '-' . time() . '.pdf';
		$filepath = $pdf_dir . '/' . $filename;

		$mpdf->Output( $filepath, \Mpdf\Output\Destination::FILE );

		return $filepath;
	}

	/**
	 * Generate HTML content for PDF
	 *
	 * @param array $patent_data Patent data.
	 * @return string HTML content.
	 */
	private function generate_html( $patent_data ) {
		ob_start();
		?>
		<!DOCTYPE html>
		<html>
		<head>
			<style>
				body { font-family: Arial, sans-serif; font-size: 12pt; }
				h1 { color: #2c3e50; font-size: 20pt; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
				h2 { color: #34495e; font-size: 16pt; margin-top: 20px; }
				table { width: 100%; border-collapse: collapse; margin-top: 10px; }
				th, td { border: 1px solid #bdc3c7; padding: 8px; text-align: left; }
				th { background-color: #ecf0f1; font-weight: bold; }
				.header { text-align: center; margin-bottom: 30px; }
				.footer { margin-top: 30px; font-size: 10pt; color: #7f8c8d; }
			</style>
		</head>
		<body>
			<div class="header">
				<h1><?php echo esc_html__( 'Patent Docket', 'synpat-platform' ); ?></h1>
				<p><?php echo esc_html( date( 'F j, Y' ) ); ?></p>
			</div>

			<h2><?php echo esc_html__( 'Patent Information', 'synpat-platform' ); ?></h2>
			<table>
				<tr>
					<th><?php echo esc_html__( 'Patent Number', 'synpat-platform' ); ?></th>
					<td><?php echo esc_html( $patent_data['patent_number'] ?? 'N/A' ); ?></td>
				</tr>
				<tr>
					<th><?php echo esc_html__( 'Title', 'synpat-platform' ); ?></th>
					<td><?php echo esc_html( $patent_data['title'] ?? 'N/A' ); ?></td>
				</tr>
				<tr>
					<th><?php echo esc_html__( 'Filing Date', 'synpat-platform' ); ?></th>
					<td><?php echo esc_html( $patent_data['filing_date'] ?? 'N/A' ); ?></td>
				</tr>
				<tr>
					<th><?php echo esc_html__( 'Issue Date', 'synpat-platform' ); ?></th>
					<td><?php echo esc_html( $patent_data['issue_date'] ?? 'N/A' ); ?></td>
				</tr>
				<tr>
					<th><?php echo esc_html__( 'Status', 'synpat-platform' ); ?></th>
					<td><?php echo esc_html( $patent_data['status'] ?? 'N/A' ); ?></td>
				</tr>
			</table>

			<h2><?php echo esc_html__( 'Abstract', 'synpat-platform' ); ?></h2>
			<p><?php echo esc_html( $patent_data['abstract'] ?? 'N/A' ); ?></p>

			<div class="footer">
				<p><?php echo esc_html__( 'Generated by SynPat Platform', 'synpat-platform' ); ?></p>
			</div>
		</body>
		</html>
		<?php
		return ob_get_clean();
	}
}
